name: Build and Deploy to local

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH no servidor
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SH_MAQUINA_LOCAL_IP }}
          username: elivandro
          key: ${{ secrets.SH_KEY }}
          script: |
            cd ~/portaria

            # Atualizar Docker Compose v2 se necessário
            if ! docker compose version >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get install -y docker-compose-plugin
            fi

            # Pull da imagem mais recente
            docker pull elivandrolopes/portaria:1.0

            # Parar e remover container antigo (ignora erro se não existir)
            docker compose stop portaria-app || true
            docker compose rm -f portaria-app || true

            # Subir container com build
            docker compose up -d --build portaria-app
